### ISSUE TITLE
Links in the footer point to wrong URL

### ISSUE THREAD

**Issue by awvwgk** [dftbplus/dftbplus.github.io#3]
The first link in the footer claims to redirect to http://www.dftbplus.org/, but redirects to https://github.com/ instead. Offending line:
https://github.com/dftbplus/dftbplus.github.io/blob/f8028dbb0d5e6b818904d9c6f611d425d3a3260b/index.html#L127

This link claims to point to the dftbplus organisation at https://github.com/dftbplus/, but actually is https://github.com/github.com/dftbplus, which yields 404. Offending line:
https://github.com/dftbplus/dftbplus.github.io/blob/f8028dbb0d5e6b818904d9c6f611d425d3a3260b/index.html#L131

**Comment by aradi** [comment]
Thanks, it should be fixed now.
